import Cocoa
import Carbon

// История буфера обмена и окно выбора. Пароли сюда не попадают:
// менеджеры паролей помечают такие записи, и мы их пропускаем,
// как и собственные временные записи приложения.
final class ClipboardHistory: NSObject, NSTableViewDataSource, NSTableViewDelegate {
    private unowned let delegate: AppDelegate
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var panel: NSPanel?
    private var table: NSTableView!
    private var returnTo: NSRunningApplication?
    private var keyMonitor: Any?

    private(set) var items: [String] = []
    private let limit = 40

    private let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    init(delegate: AppDelegate) {
        self.delegate = delegate
        super.init()
        load()
    }

    // MARK: Наблюдение

    func check() {
        guard Settings.shared.clipboardHistory else { return }
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let types = pb.types ?? []
        // Пароли и служебные записи не сохраняем
        if types.contains(concealed) || types.contains(transient) || types.contains(autoGenerated) { return }
        if IsSecureEventInputEnabled() { return }
        guard let text = pb.string(forType: .string) else { return }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, trimmed.count <= 20000 else { return }

        items.removeAll { $0 == text }
        items.insert(text, at: 0)
        if items.count > limit { items.removeLast(items.count - limit) }
        save()
    }

    func clear() {
        items.removeAll()
        save()
    }

    private var storageURL: URL {
        runtimeDirectory().appendingPathComponent("clipboard.json")
    }

    private func save() {
        guard Settings.shared.clipboardHistory else { return }
        guard let data = try? JSONEncoder().encode(items) else { return }
        try? data.write(to: storageURL, options: .atomic)
    }

    private func load() {
        guard let data = try? Data(contentsOf: storageURL),
              let saved = try? JSONDecoder().decode([String].self, from: data) else { return }
        items = saved
    }

    // MARK: Вставка

    func paste(_ index: Int) {
        guard index >= 0, index < items.count else { return }
        let text = items[index]
        let target = returnTo
        closePanel()
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.12) {
            target?.activate()
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.15) {
                let pb = NSPasteboard.general
                pb.clearContents()
                pb.setString(text, forType: .string)
                self.lastChangeCount = pb.changeCount
                self.delegate.postKey(9, flags: .maskCommand)
                self.delegate.log("буфер обмена: вставлена запись \\(index + 1)")
            }
        }
    }

    // MARK: Окно выбора

    func togglePanel() {
        if panel != nil { closePanel(); return }
        guard !items.isEmpty else {
            delegate.showPill(text: "буфер пуст", color: .systemGray)
            return
        }
        returnTo = delegate.frontApp

        let size = NSSize(width: 520, height: 320)
        let window = NSPanel(contentRect: NSRect(origin: .zero, size: size),
                             styleMask: [.titled, .closable, .nonactivatingPanel],
                             backing: .buffered, defer: false)
        window.title = "История буфера обмена"
        window.level = .floating
        window.isReleasedWhenClosed = false
        window.center()

        table = NSTableView()
        let column = NSTableColumn(identifier: NSUserInterfaceItemIdentifier("entry"))
        column.title = "Записи: 1-9 вставляют, Enter вставляет выбранную, Esc закрывает"
        column.width = size.width - 40
        table.addTableColumn(column)
        table.dataSource = self
        table.delegate = self
        table.rowHeight = 22
        table.usesAlternatingRowBackgroundColors = true
        table.doubleAction = #selector(pasteSelected)
        table.target = self

        let scroll = NSScrollView(frame: NSRect(x: 0, y: 0, width: size.width, height: size.height))
        scroll.documentView = table
        scroll.hasVerticalScroller = true
        scroll.autoresizingMask = [.width, .height]
        window.contentView = scroll
        window.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)
        table.selectRowIndexes(IndexSet(integer: 0), byExtendingSelection: false)
        panel = window

        keyMonitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { [weak self] event in
            guard let self else { return event }
            if event.keyCode == 53 { self.closePanel(); return nil }          // Esc
            if event.keyCode == 36 { self.pasteSelected(); return nil }       // Enter
            if let digit = Int(event.charactersIgnoringModifiers ?? ""), digit >= 1, digit <= 9 {
                self.paste(digit - 1)
                return nil
            }
            return event
        }
    }

    @objc private func pasteSelected() {
        paste(table.selectedRow)
    }

    private func closePanel() {
        if let keyMonitor { NSEvent.removeMonitor(keyMonitor) }
        keyMonitor = nil
        panel?.orderOut(nil)
        panel = nil
    }

    // MARK: Данные

    func numberOfRows(in tableView: NSTableView) -> Int { items.count }

    func tableView(_ tableView: NSTableView, objectValueFor column: NSTableColumn?, row: Int) -> Any? {
        let text = items[row].replacingOccurrences(of: "\\n", with: " ")
        let short = text.count > 90 ? String(text.prefix(90)) + "…" : text
        return row < 9 ? "\\(row + 1).  \\(short)" : "     \\(short)"
    }
}
